name: micro-service-task-app

services:
  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  smtp-server:
    environment:
      - MAILDEV_SMTP_PORT=1025
      - SMTP_USER=maildevuser
      - SMTP_PASS=maildevpass
      - MAILDEV_WEB_PORT=1080
    image: maildev/maildev:latest
    container_name: smtp-server
    user: root
    ports:
      - "1080:1080"   # Web UI
      - "1025:1025"   # SMTP server
    volumes:
      - mail_data:/maildata
    command: [
      "maildev",
      "--mail-directory", "/maildata",
      "--incoming-user", "${SMTP_USER}",
      "--incoming-pass", "${SMTP_PASS}"
    ]
    restart: unless-stopped

  user-service:
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    build: 
      context: ./
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    restart: unless-stopped

  task-service:
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_TASK_CREATED_QUEUE_NAME=task_created
      - RABBITMQ_TASK_UPDATED_QUEUE_NAME=task_updated
    build: 
      context: ./
      dockerfile: ./services/task-service/Dockerfile
    container_name: task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq
    restart: unless-stopped

  notification-service:
    environment:
      - NOTIFY_FROM_EMAIL=noreply@notification-service.local
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_TASK_CREATED_QUEUE_NAME=task_created
      - RABBITMQ_TASK_UPDATED_QUEUE_NAME=task_updated
      - SMTP_HOST=smtp-server
      - SMTP_PORT=1025
      - SMTP_USER=maildevuser
      - SMTP_PASS=maildevpass
    build: 
      context: ./
      dockerfile: ./services/notification-service/Dockerfile
    container_name: notification-service
    depends_on:
      - mongo
      - rabbitmq
      - smtp-server
    restart: unless-stopped

volumes:
  mongo_data:
  mail_data: