name: micro-service-task-app

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    restart: unless-stopped

  zipkin-all-in-one:
    container_name: zipkin-all-in-one
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    restart: unless-stopped
    
  otel-collector:
    container_name: otel-collector
    image: ${OTELCOL_IMG}
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:8.0-ubi8
    ports:
      - "${MONGODB__PORT}:27017"
    secrets:
      - source: mongo_pem
        target: mongo.pem
      - source: ca_cert
        target: ca.cert.pem
    volumes:
      - mongo_data:/data/db
    command:
      - mongod
      - --bind_ip_all
      - --tlsMode
      - requireTLS
      - --tlsCertificateKeyFile
      - /run/secrets/mongo.pem
      - --tlsCAFile
      - /run/secrets/ca.cert.pem
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2-management-alpine
    ports:
      - "${RABBITMQ__PORT}:5671"
      - "${RABBITMQ__WEB_PORT}:15672"
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: rabbitmq_cert
        target: rabbitmq.cert.pem
      - source: rabbitmq_key
        target: rabbitmq.key.pem
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    restart: unless-stopped

  smtp-server:
    container_name: smtp-server
    image: maildev/maildev:latest
    environment:
      - MAILDEV_SMTP_PORT=${SMTP__PORT}
      - SMTP__USER=${SMTP__USER}
      - SMTP__PASS=${SMTP__PASS}
      - MAILDEV_WEB_PORT=${MAILDEV_WEB_PORT}
    ports:
      - "${MAILDEV_WEB_PORT}:1080" # Web UI
      - "${SMTP__PORT}:1025" # SMTP server
    volumes:
      - mail_data:/maildata
    command:
      [
        "maildev",
        "--mail-directory",
        "/maildata",
        "--incoming-user",
        "${SMTP__USER}",
        "--incoming-pass",
        "${SMTP__PASS}",
      ]
    user: root
    restart: unless-stopped

  oauth-service:
    container_name: oauth-service
    profiles: [full]
    ports:
      - "${OAUTH_SVC__PORT}:3001"
    environment:
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - OAUTH_SVC__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - OAUTH_SVC__PRIVATE_KEY_PATH=/run/secrets/oauth-service.key.pem
      - OAUTH_SVC__CERT_PATH=/run/secrets/oauth-service.cert.pem
      - OAUTH_SVC__KEY_CERT_COMBO_PATH=/run/secrets/oauth-service.pem
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: oauth_svc_cert
        target: oauth-service.cert.pem
      - source: oauth_svc_key
        target: oauth-service.key.pem
      - source: oauth_svc_pem
        target: oauth-service.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_oauth_service
    depends_on:
      - mongo
      - otel-collector
    restart: unless-stopped

  task-service:
    container_name: task-service
    profiles: [full]
    ports:
      - "${TASK_SVC__PORT}:3002"
    environment:
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - RABBITMQ__HOST=${RABBITMQ__HOST}
      - RABBITMQ__PORT=${RABBITMQ__PORT}
      - RABBITMQ__TASK_CREATED_QUEUE_NAME=${RABBITMQ__TASK_CREATED_QUEUE_NAME}
      - RABBITMQ__TASK_UPDATED_QUEUE_NAME=${RABBITMQ__TASK_UPDATED_QUEUE_NAME}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - TASK_SVC__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - TASK_SVC__PRIVATE_KEY_PATH=/run/secrets/task-service.key.pem
      - TASK_SVC__CERT_PATH=/run/secrets/task-service.cert.pem
      - TASK_SVC__KEY_CERT_COMBO_PATH=/run/secrets/task-service.pem
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: task_svc_cert
        target: task-service.cert.pem
      - source: task_svc_key
        target: task-service.key.pem
      - source: task_svc_pem
        target: task-service.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_task_service
    depends_on:
      - mongo
      - rabbitmq
      - otel-collector
    restart: unless-stopped

  notification-service:
    container_name: notification-service
    profiles: [full]
    environment:
      - NOTIFY_SVC__FROM_EMAIL=noreply@notification-service.local
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - RABBITMQ__HOST=${RABBITMQ__HOST}
      - RABBITMQ__PORT=${RABBITMQ__PORT}
      - RABBITMQ__TASK_CREATED_QUEUE_NAME=${RABBITMQ__TASK_CREATED_QUEUE_NAME}
      - RABBITMQ__TASK_UPDATED_QUEUE_NAME=${RABBITMQ__TASK_UPDATED_QUEUE_NAME}
      - SMTP__HOST=${SMTP__HOST}
      - SMTP__PORT=${SMTP__PORT}
      - SMTP__USER=${SMTP__USER}
      - SMTP__PASS=${SMTP__PASS}
      - NOTIFY_SVC__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - NOTIFY_SVC__PRIVATE_KEY_PATH=/run/secrets/notification-service.key.pem
      - NOTIFY_SVC__CERT_PATH=/run/secrets/notification-service.cert.pem
      - NOTIFY_SVC__KEY_CERT_COMBO_PATH=/run/secrets/notification-service.pem
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: notify_svc_cert
        target: notification-service.cert.pem
      - source: notify_svc_key
        target: notification-service.key.pem
      - source: notify_svc_pem
        target: notification-service.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_notification_service
    depends_on:
      - mongo
      - rabbitmq
      - smtp-server
      - otel-collector
    restart: unless-stopped

  web-ui:
    container_name: web-ui
    profiles: [full]
    ports:
      - "${WEB_UI__PORT}:3000"
    environment:
      - WEB_UI__PORT=${WEB_UI__PORT}
      - OAUTH_SVC__PORT=${OAUTH_SVC__PORT}
      - TASK_SVC__PORT=${TASK_SVC__PORT}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - WEB_UI__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - WEB_UI__PRIVATE_KEY_PATH=/run/secrets/web-ui.key.pem
      - WEB_UI__CERT_PATH=/run/secrets/web-ui.cert.pem
      - WEB_UI__KEY_CERT_COMBO_PATH=/run/secrets/web-ui.pem
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: web_ui_cert
        target: web-ui.cert.pem
      - source: web_ui_key
        target: web-ui.key.pem
      - source: web_ui_pem
        target: web-ui.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_web_ui
      args:
        - WEB_UI__CA_CERT_PATH=/run/secrets/ca.cert.pem
        - WEB_UI__PRIVATE_KEY_PATH=/run/secrets/web-ui.key.pem
        - WEB_UI__CERT_PATH=/run/secrets/web-ui.cert.pem
        - WEB_UI__KEY_CERT_COMBO_PATH=/run/secrets/web-ui.pem
      secrets:
        - source: ca_cert
          target: ca.cert.pem
        - source: web_ui_cert
          target: web-ui.cert.pem
        - source: web_ui_key
          target: web-ui.key.pem
        - source: web_ui_pem
          target: web-ui.pem
    depends_on:
      - oauth-service
      - task-service
      - otel-collector
    restart: unless-stopped

volumes:
  mongo_data:
  mail_data:
  npm_cache:

secrets:
  ca_cert:
    file: ./.certs/ca/ca.cert.pem
  
  mongo_pem:
    file: ./.certs/mongo/mongo.pem

  rabbitmq_cert:
    file: ./.certs/rabbitmq/rabbitmq.cert.pem
  rabbitmq_key:
    file: ./.certs/rabbitmq/rabbitmq.key.pem
  
  oauth_svc_cert:
    file: ./.certs/oauth-service/oauth-service.cert.pem
  oauth_svc_key:
    file: ./.certs/oauth-service/oauth-service.key.pem
  oauth_svc_pem:
    file: ./.certs/oauth-service/oauth-service.pem
  
  task_svc_cert:
    file: ./.certs/task-service/task-service.cert.pem
  task_svc_key:
    file: ./.certs/task-service/task-service.key.pem
  task_svc_pem:
    file: ./.certs/task-service/task-service.pem
  
  notify_svc_cert:
    file: ./.certs/notification-service/notification-service.cert.pem
  notify_svc_key:
    file: ./.certs/notification-service/notification-service.key.pem
  notify_svc_pem:
    file: ./.certs/notification-service/notification-service.pem
  
  web_ui_cert:
    file: ./.certs/web-ui/web-ui.cert.pem
  web_ui_key:
    file: ./.certs/web-ui/web-ui.key.pem
  web_ui_pem:
    file: ./.certs/web-ui/web-ui.pem
