name: micro-service-task-app

services:
  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    restart: unless-stopped

  smtp-server:
    environment:
      - MAILDEV_SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - MAILDEV_WEB_PORT=${MAILDEV_WEB_PORT}
    image: maildev/maildev:latest
    container_name: smtp-server
    user: root
    ports:
      - "${MAILDEV_WEB_PORT}:1080"   # Web UI
      - "${SMTP_PORT}:1025"   # SMTP server
    volumes:
      - mail_data:/maildata
    command: [
      "maildev",
      "--mail-directory", "/maildata",
      "--incoming-user", "${SMTP_USER}",
      "--incoming-pass", "${SMTP_PASS}"
    ]
    restart: unless-stopped

  user-service:
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
    build: 
      context: ./
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    ports:
      - "${USER_SVC_PORT}:3001"
    depends_on:
      - mongo
    restart: unless-stopped

  task-service:
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_TASK_CREATED_QUEUE_NAME=${RABBITMQ_TASK_CREATED_QUEUE_NAME}
      - RABBITMQ_TASK_UPDATED_QUEUE_NAME=${RABBITMQ_TASK_UPDATED_QUEUE_NAME}
    build: 
      context: ./
      dockerfile: ./services/task-service/Dockerfile
    container_name: task-service
    ports:
      - "${TASK_SVC_PORT}:3002"
    depends_on:
      - mongo
      - rabbitmq
    restart: unless-stopped

  notification-service:
    environment:
      - NOTIFY_FROM_EMAIL=noreply@notification-service.local
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_TASK_CREATED_QUEUE_NAME=${RABBITMQ_TASK_CREATED_QUEUE_NAME}
      - RABBITMQ_TASK_UPDATED_QUEUE_NAME=${RABBITMQ_TASK_UPDATED_QUEUE_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    build: 
      context: ./
      dockerfile: ./services/notification-service/Dockerfile
    container_name: notification-service
    depends_on:
      - mongo
      - rabbitmq
      - smtp-server
    restart: unless-stopped

volumes:
  mongo_data:
  mail_data: