name: micro-service-task-app

services:
  mongo:
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    image: mongodb/mongodb-community-server:8.0-ubi8
    ports:
      - "${MONGODB_PORT}:27017"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2-management-alpine
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_WEB_PORT}:15672"
    restart: unless-stopped

  smtp-server:
    container_name: smtp-server
    environment:
      - MAILDEV_SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - MAILDEV_WEB_PORT=${MAILDEV_WEB_PORT}
    volumes:
      - mail_data:/maildata
    image: maildev/maildev:latest
    user: root
    ports:
      - "${MAILDEV_WEB_PORT}:1080" # Web UI
      - "${SMTP_PORT}:1025" # SMTP server
    command:
      [
        "maildev",
        "--mail-directory",
        "/maildata",
        "--incoming-user",
        "${SMTP_USER}",
        "--incoming-pass",
        "${SMTP_PASS}",
      ]
    restart: unless-stopped

  oauth-service:
    container_name: oauth-service
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_oauth_service
    ports:
      - "${OAUTH_SVC_PORT}:3001"
    depends_on:
      - mongo
    restart: unless-stopped

  task-service:
    container_name: task-service
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_TASK_CREATED_QUEUE_NAME=${RABBITMQ_TASK_CREATED_QUEUE_NAME}
      - RABBITMQ_TASK_UPDATED_QUEUE_NAME=${RABBITMQ_TASK_UPDATED_QUEUE_NAME}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_task_service
    ports:
      - "${TASK_SVC_PORT}:3002"
    depends_on:
      - mongo
      - rabbitmq
    restart: unless-stopped

  notification-service:
    container_name: notification-service
    environment:
      - NOTIFY_FROM_EMAIL=noreply@notification-service.local
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_TASK_CREATED_QUEUE_NAME=${RABBITMQ_TASK_CREATED_QUEUE_NAME}
      - RABBITMQ_TASK_UPDATED_QUEUE_NAME=${RABBITMQ_TASK_UPDATED_QUEUE_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_notification_service
    depends_on:
      - mongo
      - rabbitmq
      - smtp-server
    restart: unless-stopped

  web-ui:
    environment:
      - WEB_UI_PORT=${WEB_UI_PORT}
      - OAUTH_SVC_PORT=${OAUTH_SVC_PORT}
      - TASK_SVC_PORT=${TASK_SVC_PORT}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_web_ui
    container_name: web-ui
    ports:
      - "${WEB_UI_PORT}:3000"
    depends_on:
      - oauth-service
      - task-service
    restart: unless-stopped

volumes:
  mongo_data:
  mail_data:
  npm_cache:
