name: micro-service-task-app

services:
  init-volumes:
    container_name: init-volumes
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: init_volumes
    networks:
      - backend
    command:
      - sh
      - -c
      - /run/init-volumes.sh
    volumes:
      - ./backend-config/init-volumes.sh:/run/init-volumes.sh:ro
      - service_logs:/run/logs
      - mongo_logs:/var/log/mongodb/

  openobserve:
    container_name: openobserve
    image: public.ecr.aws/zinclabs/openobserve:latest
    networks:
      - backend
    ports:
      - "${ZO_WEB_PORT}:5080"
      - "${ZO_GRPC_PORT}:5081"
    environment:
      - ZO_TELEMETRY=false
      #- ZO_ALLOW_USER_DEFINED_STREAMS=true
      - ZO_DATA_DIR=/run/data
      - ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL}
      - ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD}
      - ZO_COLS_PER_RECORD_LIMIT=${ZO_COLS_PER_RECORD_LIMIT}
      - ZO_LOGS_FILE_RETENTION=${ZO_LOGS_FILE_RETENTION}
      - ZO_TRACES_FILE_RETENTION=${ZO_TRACES_FILE_RETENTION}
      - ZO_LOG_JSON_FORMAT=${ZO_LOG_JSON_FORMAT}
      - ZO_RUM_ENABLED=${ZO_RUM_ENABLED}
      - ZO_RUM_INSECURE_HTTP=${ZO_RUM_INSECURE_HTTP}
    volumes:
      - openobserve_data:/run/data
    restart: unless-stopped

  otel-collector:
    container_name: otel-collector
    image: ${OTELCOL_IMG}
    networks:
      - backend
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    environment:
      - ZO_HOST=${ZO_HOST}
      - ZO_GRPC_PORT=${ZO_GRPC_PORT}
      - ZO_OTEL_TOKEN=${ZO_OTEL_TOKEN}
      - ZO_OTEL_ORGANIZATION=${ZO_OTEL_ORGANIZATION}
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - MONGODB__OTEL_COLLECTOR_PASSWORD=${MONGODB__OTEL_COLLECTOR_PASSWORD}
    volumes:
      - ./backend-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - mongo_logs:/var/log/mongodb/
      - rabbitmq_logs:/var/log/rabbitmq/
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: otel_collector_cert
        target: otel-collector.cert.pem
      - source: otel_collector_key
        target: otel-collector.key.pem
      - source: otel_collector_pem
        target: otel-collector.pem
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    depends_on:
      init-volumes:
        condition: service_completed_successfully
      openobserve:
        condition: service_started
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:8.0-ubi8
    networks:
      - backend
    ports:
      - "${MONGODB__PORT}:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB__INITDB_ROOT_USERNAME
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB__INITDB_ROOT_PASSWORD
      - OTEL_COLLECTOR_PASSWORD=${MONGODB__OTEL_COLLECTOR_PASSWORD}
    secrets:
      - source: mongo_pem
        target: mongo.pem
      - source: ca_cert
        target: ca.cert.pem
    volumes:
      - ./backend-config/mongod.conf:/etc/mongod.conf:ro
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb/
    command:
      - mongod
      - --config
      - /etc/mongod.conf
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --tls --tlsCAFile /run/secrets/ca.cert.pem --tlsCertificateKeyFile /run/secrets/mongo.pem admin --eval \"quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)\" || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  mongo-init-users:
    container_name: mongo-init-users
    networks:
      - backend
    depends_on:
      mongo:
        condition: service_healthy
      init-volumes:
        condition: service_completed_successfully
    image: mongodb/mongodb-community-server:8.0-ubi8
    command:
      - sh
      - -c
      - /run/init-mongo-users.sh
    environment:
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB__INITDB_ROOT_USERNAME
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB__INITDB_ROOT_PASSWORD
      - MONGODB__OTEL_COLLECTOR_PASSWORD=${MONGODB__OTEL_COLLECTOR_PASSWORD}
    volumes:
      - ./backend-config/init-mongo-users.sh:/run/init-mongo-users.sh:ro
    secrets:
      - source: mongo_pem
        target: mongo.pem
      - source: ca_cert
        target: ca.cert.pem
    restart: no

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2-management-alpine
    networks:
      - backend
    ports:
      - "${RABBITMQ__PORT}:5671"
      - "${RABBITMQ__WEB_PORT}:15672"
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: rabbitmq_cert
        target: rabbitmq.cert.pem
      - source: rabbitmq_key
        target: rabbitmq.key.pem
    volumes:
      - ./backend-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_logs:/var/log/rabbitmq/
    restart: unless-stopped

  smtp-server:
    container_name: smtp-server
    image: maildev/maildev:latest
    networks:
      - backend
    ports:
      - "${MAILDEV_WEB_PORT}:1080" # Web UI
      - "${SMTP__PORT}:1025" # SMTP server
    environment:
      - MAILDEV_SMTP_PORT=${SMTP__PORT}
      - SMTP__USER=${SMTP__USER}
      - SMTP__PASS=${SMTP__PASS}
      - MAILDEV_WEB_PORT=${MAILDEV_WEB_PORT}
    volumes:
      - mail_data:/maildata
    command:
      [
        "maildev",
        "--mail-directory",
        "/maildata",
        "--incoming-user",
        "${SMTP__USER}",
        "--incoming-pass",
        "${SMTP__PASS}",
      ]
    user: root
    restart: unless-stopped

  oauth-service:
    container_name: oauth-service
    profiles: [full]
    networks:
      - backend
    ports:
      - "${OAUTH_SVC__PORT}:3001"
    environment:
      - OAUTH_SVC__LOG_PATH=${OAUTH_SVC__LOG_PATH}
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - RABBITMQ__HOST=${RABBITMQ__HOST}
      - RABBITMQ__PORT=${RABBITMQ__PORT}
      - RABBITMQ__ACCOUNT_LINKED_QUEUE_NAME=${RABBITMQ__ACCOUNT_LINKED_QUEUE_NAME}
      - OAUTH_SVC__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - OAUTH_SVC__PRIVATE_KEY_PATH=/run/secrets/oauth-service.key.pem
      - OAUTH_SVC__CERT_PATH=/run/secrets/oauth-service.cert.pem
      - OAUTH_SVC__KEY_CERT_COMBO_PATH=/run/secrets/oauth-service.pem
      - NOTIFY_SVC__HOST=${NOTIFY_SVC__HOST}
      - NOTIFY_SVC__PORT=${NOTIFY_SVC__PORT}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    volumes:
      - service_logs:/run/logs
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: oauth_svc_cert
        target: oauth-service.cert.pem
      - source: oauth_svc_key
        target: oauth-service.key.pem
      - source: oauth_svc_pem
        target: oauth-service.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_oauth_service
    depends_on:
      mongo:
        condition: service_healthy
      init-volumes:
        condition: service_completed_successfully
      mongo-init-users:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -k --cert /run/secrets/oauth-service.cert.pem --key /run/secrets/oauth-service.key.pem --silent --fail \"https://localhost:3001/ping\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    restart: unless-stopped

  task-service:
    container_name: task-service
    profiles: [full]
    networks:
      - backend
    ports:
      - "${TASK_SVC__PORT}:3002"
    environment:
      - TASK_SVC__LOG_PATH=${TASK_SVC__LOG_PATH}
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - RABBITMQ__HOST=${RABBITMQ__HOST}
      - RABBITMQ__PORT=${RABBITMQ__PORT}
      - RABBITMQ__TASK_CREATED_QUEUE_NAME=${RABBITMQ__TASK_CREATED_QUEUE_NAME}
      - RABBITMQ__TASK_UPDATED_QUEUE_NAME=${RABBITMQ__TASK_UPDATED_QUEUE_NAME}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - TASK_SVC__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - TASK_SVC__PRIVATE_KEY_PATH=/run/secrets/task-service.key.pem
      - TASK_SVC__CERT_PATH=/run/secrets/task-service.cert.pem
      - TASK_SVC__KEY_CERT_COMBO_PATH=/run/secrets/task-service.pem
      - NOTIFY_SVC__HOST=${NOTIFY_SVC__HOST}
      - NOTIFY_SVC__PORT=${NOTIFY_SVC__PORT}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    volumes:
      - service_logs:/run/logs
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: task_svc_cert
        target: task-service.cert.pem
      - source: task_svc_key
        target: task-service.key.pem
      - source: task_svc_pem
        target: task-service.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_task_service
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      init-volumes:
        condition: service_completed_successfully
      mongo-init-users:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -k --cert /run/secrets/task-service.cert.pem --key /run/secrets/task-service.key.pem --silent --fail \"https://localhost:3002/ping\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    restart: unless-stopped

  notification-service:
    container_name: notification-service
    profiles: [full]
    networks:
      - backend
    ports:
      - "${NOTIFY_SVC__PORT}:3003"
    environment:
      - NOTIFY_SVC__LOG_PATH=${NOTIFY_SVC__LOG_PATH}
      - NOTIFY_SVC__FROM_EMAIL=noreply@notification-service.local
      - MONGODB__HOST=${MONGODB__HOST}
      - MONGODB__PORT=${MONGODB__PORT}
      - RABBITMQ__HOST=${RABBITMQ__HOST}
      - RABBITMQ__PORT=${RABBITMQ__PORT}
      - RABBITMQ__TASK_CREATED_QUEUE_NAME=${RABBITMQ__TASK_CREATED_QUEUE_NAME}
      - RABBITMQ__TASK_UPDATED_QUEUE_NAME=${RABBITMQ__TASK_UPDATED_QUEUE_NAME}
      - RABBITMQ__ACCOUNT_LINKED_QUEUE_NAME=${RABBITMQ__ACCOUNT_LINKED_QUEUE_NAME}
      - SMTP__HOST=${SMTP__HOST}
      - SMTP__PORT=${SMTP__PORT}
      - SMTP__USER=${SMTP__USER}
      - SMTP__PASS=${SMTP__PASS}
      - NOTIFY_SVC__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - NOTIFY_SVC__PRIVATE_KEY_PATH=/run/secrets/notification-service.key.pem
      - NOTIFY_SVC__CERT_PATH=/run/secrets/notification-service.cert.pem
      - NOTIFY_SVC__KEY_CERT_COMBO_PATH=/run/secrets/notification-service.pem
      - NOTIFY_SVC__HOST=${NOTIFY_SVC__HOST}
      - NOTIFY_SVC__PORT=${NOTIFY_SVC__PORT}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    volumes:
      - service_logs:/run/logs
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: notify_svc_cert
        target: notification-service.cert.pem
      - source: notify_svc_key
        target: notification-service.key.pem
      - source: notify_svc_pem
        target: notification-service.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_notification_service
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      smtp-server:
        condition: service_started
      init-volumes:
        condition: service_completed_successfully
      mongo-init-users:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -k --cert /run/secrets/notification-service.cert.pem --key /run/secrets/notification-service.key.pem --silent --fail \"https://localhost:3003/ping\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    restart: unless-stopped

  web-ui:
    container_name: web-ui
    profiles: [full]
    networks:
      - backend
    ports:
      - "${WEB_UI__PORT}:3000"
    environment:
      - WEB_UI__LOG_PATH=${WEB_UI__LOG_PATH}
      - WEB_UI__PORT=${WEB_UI__PORT}
      - OAUTH_SVC__PORT=${OAUTH_SVC__PORT}
      - TASK_SVC__PORT=${TASK_SVC__PORT}
      - AUTH_TRUST_HOST=true
      - AUTH_URL=${AUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - WEB_UI__CA_CERT_PATH=/run/secrets/ca.cert.pem
      - WEB_UI__PRIVATE_KEY_PATH=/run/secrets/web-ui.key.pem
      - WEB_UI__CERT_PATH=/run/secrets/web-ui.cert.pem
      - WEB_UI__KEY_CERT_COMBO_PATH=/run/secrets/web-ui.pem
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    volumes:
      - service_logs:/run/logs
    secrets:
      - source: ca_cert
        target: ca.cert.pem
      - source: web_ui_cert
        target: web-ui.cert.pem
      - source: web_ui_key
        target: web-ui.key.pem
      - source: web_ui_pem
        target: web-ui.pem
    labels:
      - "buildkit.cache.to=type=local,dest=./npm-cache"
      - "buildkit.cache.from=type=local,src=./npm-cache"
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: runtime_web_ui
      args:
        - WEB_UI__CA_CERT_PATH=/run/secrets/ca.cert.pem
        - WEB_UI__PRIVATE_KEY_PATH=/run/secrets/web-ui.key.pem
        - WEB_UI__CERT_PATH=/run/secrets/web-ui.cert.pem
        - WEB_UI__KEY_CERT_COMBO_PATH=/run/secrets/web-ui.pem
      secrets:
        - source: ca_cert
          target: ca.cert.pem
        - source: web_ui_cert
          target: web-ui.cert.pem
        - source: web_ui_key
          target: web-ui.key.pem
        - source: web_ui_pem
          target: web-ui.pem
    depends_on:
      oauth-service:
        condition: service_healthy
      task-service:
        condition: service_healthy
      init-volumes:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "curl -k --silent --fail \"http://localhost:3000/ping\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    restart: unless-stopped

networks:
  backend:

volumes:
  mongo_data:
  mongo_logs:
  rabbitmq_logs:
  mail_data:
  npm_cache:
  openobserve_data:
  service_logs:

secrets:
  ca_cert:
    file: ./.certs/ca/ca.cert.pem
  
  mongo_pem:
    file: ./.certs/mongo/mongo.pem

  rabbitmq_cert:
    file: ./.certs/rabbitmq/rabbitmq.cert.pem
  rabbitmq_key:
    file: ./.certs/rabbitmq/rabbitmq.key.pem
  
  oauth_svc_cert:
    file: ./.certs/oauth-service/oauth-service.cert.pem
  oauth_svc_key:
    file: ./.certs/oauth-service/oauth-service.key.pem
  oauth_svc_pem:
    file: ./.certs/oauth-service/oauth-service.pem
  
  task_svc_cert:
    file: ./.certs/task-service/task-service.cert.pem
  task_svc_key:
    file: ./.certs/task-service/task-service.key.pem
  task_svc_pem:
    file: ./.certs/task-service/task-service.pem
  
  notify_svc_cert:
    file: ./.certs/notification-service/notification-service.cert.pem
  notify_svc_key:
    file: ./.certs/notification-service/notification-service.key.pem
  notify_svc_pem:
    file: ./.certs/notification-service/notification-service.pem
  
  web_ui_cert:
    file: ./.certs/web-ui/web-ui.cert.pem
  web_ui_key:
    file: ./.certs/web-ui/web-ui.key.pem
  web_ui_pem:
    file: ./.certs/web-ui/web-ui.pem

  otel_collector_cert:
    file: ./.certs/otel-collector/otel-collector.cert.pem
  otel_collector_key:
    file: ./.certs/otel-collector/otel-collector.key.pem
  otel_collector_pem:
    file: ./.certs/otel-collector/otel-collector.pem
