service:
  extensions: [basicauth/os, jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: debug

extensions:
  healthcheckv2:
    use_v2: true
    http:

  basicauth/os:
    client_auth:
      username: ${OPENSEARCH__ADMIN_USER}
      password: ${OPENSEARCH__ADMIN_PASS}

  jaeger_query:
    storage:
      traces: trace_storage
      metrics: metric_storage
    ui:
      config_file: /etc/jaeger/jaeger-ui.json

  jaeger_storage:
    # Configure trace storage to use the OpenSearch instance from docker-compose
    backends:
      trace_storage: &opensearch_config
        opensearch:
          # OpenSearch container & port as defined in docker-compose.yml
          server_urls: ["https://${OPENSEARCH__HOST}:${OPENSEARCH__HTTP_PORT}"]
          auth:
            authenticator: basicauth/os
          # TLS settings: use the CA provided as a Docker secret in compose
          tls:
            insecure_skip_verify: false
            ca_file: /run/secrets/ca.cert.pem
            cert_file: /run/secrets/jaeger.cert.pem
            key_file: /run/secrets/jaeger.key.pem
          indices:
            index_prefix: "jaeger-main"
            spans:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            services:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            dependencies:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            sampling:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1

      trace_archive:
        opensearch:
          server_urls: ["https://${OPENSEARCH__HOST}:${OPENSEARCH__HTTP_PORT}"]
          auth:
            authenticator: basicauth/os
          tls:
            insecure_skip_verify: false
            insecure: false
            ca_file: /run/secrets/ca.cert.pem
            cert_file: /run/secrets/jaeger.cert.pem
            key_file: /run/secrets/jaeger.key.pem
          indices:
            index_prefix: "jaeger-archive"
    
    # Use the same OpenSearch back-end as traces for the metrics back-end
    metric_backends:
      metric_storage: *opensearch_config

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: trace_storage
  
  debug:
    verbosity: basic