receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  filelog/mongodb_json:
    include:
      - /var/log/mongodb/*.log
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.t.$date # MongoDB JSON log field for timestamp (use the nested $date string)
          layout: '%Y-%m-%dT%H:%M:%S.%L%z' # Example layout, adjust to match your exact format
        severity:
          parse_from: attributes.s
          overwrite_text: true
          preset: none
          mapping:
            debug: D1
            debug2: D2
            debug3: D3
            debug4:
              - D4
              - D5
            info: I
            warn: W
            error: E
            fatal: F

      # remove fields parsed by json_parser operator above
      - type: remove
        field: attributes.t

      - type: remove
        field: attributes.s

      - type: add
        field: resource['service.name']
        value: mongodb

      - type: move
        from: attributes.id
        to: attributes.mongo_log_id

      - type: move
        from: attributes.c
        to: attributes.component.name

      - type: move
        from: attributes.ctx
        to: attributes.thread.name

      - type: flatten
        field: attributes.attr.message
        if: '"attr" in attributes && "message" in attributes.attr'

      - type: flatten
        field: attributes.attr
        if: '"attr" in attributes'

      - type: move
        from: attributes.pid
        to: resource['process.pid']
        if: '"pid" in attributes'

      - type: move # Move the log message to the main body field
        from: attributes.msg
        to: body

  filelog/rabbitmq:
    include:
      - /var/log/rabbitmq/*.log
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout_type: epoch
          layout: us
        severity:
          parse_from: attributes.level
          overwrite_text: true
          mapping:
            warn:
              - warning
            fatal:
              - critical
      
      - type: remove
        field: attributes.time

      - type: remove
        field: attributes.level

      - type: add
        field: resource['service.name']
        value: rabbitmq
      
      - type: move
        from: attributes.msg
        to: body
      
      - type: move
        from: attributes.pid
        to: resource['process.pid']
        if: '"pid" in attributes'
      
      - type: move
        from: attributes.domain
        to: attributes.rabbitmq_domain
      
      - type: move
        from: attributes.file
        to: attributes.code.file.path
        if: '"file" in attributes'

      - type: move
        from: attributes.line
        to: attributes.code.line.number
        if: '"line" in attributes'

      - type: add
        field: attributes.code.function.name
        value: EXPR(attributes.mfa[0] + ":" + attributes.mfa[1] + "/" + string(int(attributes.mfa[2])))
        if: '"mfa" in attributes'

      - type: remove
        field: attributes.mfa
        if: '"mfa" in attributes'

exporters:
  debug:
    verbosity: basic

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  opensearch/logs:
    logs_index: "logs-stream"
    http:
      endpoint: "https://opensearch:9200"
      # retry_on_failure: true
      auth:
        authenticator: basicauth/os
      tls:
        insecure: false
        ca_file: /run/secrets/ca.cert.pem
        cert_file: /run/secrets/otel-collector.cert.pem
        key_file: /run/secrets/otel-collector.key.pem

  prometheus:
    endpoint: "0.0.0.0:9464"
    tls:
      ca_file: /run/secrets/ca.cert.pem
      cert_file: /run/secrets/otel-collector.cert.pem
      key_file: /run/secrets/otel-collector.key.pem

processors:
  batch:

extensions:
  health_check:
  
  basicauth/os:
    client_auth:
      username: ${OPENSEARCH__ADMIN_USER}
      password: ${OPENSEARCH__ADMIN_PASS}

service:
  extensions: [health_check, basicauth/os]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp, filelog/mongodb_json, filelog/rabbitmq]
      processors: []
      exporters: [debug, opensearch/logs]
