receivers:
  filelog/mongodb_json:
    include:
      - /var/log/mongodb/*.log
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.t.$date # MongoDB JSON log field for timestamp (use the nested $date string)
          layout: '%Y-%m-%dT%H:%M:%S.%L%z' # Example layout, adjust to match your exact format
      - type: add
        field: resource.service.name
        value: mongodb
      - type: move # Move the parsed timestamp to the main timestamp field
        from: attributes.t.$date
        to: attributes.timestamp
      - type: move # Move the log message to the main body field
        from: attributes.msg
        to: body.msg
      - type: move
        from: attributes.attr.message
        to: body
        on_error: send_quiet

  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        

exporters:
  debug:
    verbosity: basic

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  opensearch/logs:
    logs_index: "logs-stream"
    http:
      endpoint: "https://opensearch:9200"
      # retry_on_failure: true
      auth:
        authenticator: basicauth/os
      tls:
        insecure: false
        ca_file: /run/secrets/ca.cert.pem
        cert_file: /run/secrets/otel-collector.cert.pem
        key_file: /run/secrets/otel-collector.key.pem

  prometheus:
    endpoint: "0.0.0.0:9464"
    tls:
      ca_file: /run/secrets/ca.cert.pem
      cert_file: /run/secrets/otel-collector.cert.pem
      key_file: /run/secrets/otel-collector.key.pem

processors:
  batch:

extensions:
  health_check:
  
  basicauth/os:
    client_auth:
      username: ${OPENSEARCH__ADMIN_USER}
      password: ${OPENSEARCH__ADMIN_PASS}

service:
  extensions: [health_check, basicauth/os]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp, filelog/mongodb_json]
      processors: []
      exporters: [debug, opensearch/logs]
