global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:9464']
    tls_config:
      ca_file: /run/secrets/ca.cert.pem
      cert_file: /run/secrets/prometheus.cert.pem
      key_file: /run/secrets/prometheus.key.pem
      insecure_skip_verify: false
